### ISSUE TITLE
Commands not working if guild is not in the DB

### ISSUE THREAD

**Issue by AndreasGassmann** [SideProjectGuys/invite-manager-bot#63]
Today we had some issues because we didn't get some guildjoin events, which means the guilds were not in our DB and the foreign keys were invalid after that.

Maybe we could make that less strict in some cases (eg logs).

**Comment by Valandur** [comment]
I just ran into this issue aswell. The logs were trying to be inserted for a guild that wasn't present in the DB, I didn't realize it's because of the missing join events.
I think asserting that the guild is created is the better approach, because this issue will not only be a problem for logs. I will add an insert for the guilds to the logs.
